export enum RegisterTextsEnum {
    title = "criar uma",
    title2 = "conta",
    iptName = "seu nome",
    iptNickname = "usuário",
    iptEmail = "email",
    iptPassword = "senha",
    iptConfirmPassword = "confirme a senha",
    btnLabel = "criar uma conta",
    linkLabel1 = "ou caso você ",
    linkLabel2 = "já tenha uma conta",
    shortNameMsg = "nome muito curto",
    requiredName = "o nome completo é obrigatório",
    shortNickname = "o nome de usuário deve ter no minimo 4 caracteres",
    longNickname = "nome de usuário deve ter no máximo 12 caracteres",
    requiredNickname = "o nome de usuário é obrigatório",
    cantSpaceNickname = "o nome de usuário não pode conter espaços",
    invalidEmail = "email inválido",
    requiredEmail = "o endereço de e-mail é obrigatório",
    requiredPassword = "a senha é obrigatória",
    dontMatchPasswords = "As senhas não coincidem",
    successMsg = "Conta criada com sucesso",
}